name: 签到

on:
  schedule:
    - cron: '0 0 * * *'  # UTC时间，对应北京时间8点
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install axios
          npm install undici

      - name: Checkin mediastorm
        run: node mediastorm.js
        env:
          YSJFCS: ${{ secrets.YSJFCS }}

      - name: Checkin sharge
        run: node sharge.js
        env:
          SHARGE: ${{ secrets.SHARGE }}
        
      - name: Checkin 58moto
        run: node 58moto.js
        env:
          MTF: ${{ secrets.MTF }}

      - name: Checkin aima
        run: node aima.js
        env:
          AIMA: ${{ secrets.AIMA }}

      - name: Send message to serverchan
        run: node push_to_serverchan.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
